apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chesspro.backend.fullname" . }}-config
  labels:
    {{- include "chesspro.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  APP_ENV: {{ .Values.config.appEnv | quote }}
  STOCKFISH_PATH: {{ .Values.config.stockfishPath | quote }}
