apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chesspro
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rpmwin/chessPRO
    targetRevision: HEAD
    path: helm/chesspro
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: chesspro
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
